name: CI

on: push

jobs:   
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   
      
      - run: |
          mkdir -p logs/
      - name: Safety
        run: |
         pip install safety
         safety check -r Environment/App/app/flask/requirements.txt > logs/result-safety.txt
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result.txt   
          
